language: android
android:
        components:
                - tools
                - platform-tools
                - build-tools-25.0.2
                - android-25
                - android-21
                - extra-android-m2repository
                - extra-google-android-support
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
jdk:
  - oraclejdk8